# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - openhackcaepoi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://openhackcaeacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3bca51d0867c4875ac3c62685ccbac28 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_db5467e4bc574c639df55ea6a2618bcf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: openhackcaeacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3bca51d0867c4875ac3c62685ccbac28 }}/devopsoh/api-poi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackcaepoi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1855eeed0e204c6a91a220e6c81926b2 }}
        images: 'openhackcaeacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3bca51d0867c4875ac3c62685ccbac28 }}/devopsoh/api-poi:${{ github.sha }}'